import os
STRICT_PHYSICS_VALIDATION = os.getenv("IRIS_STRICT_PHYSICS", "1") == "1"
CANDIDATE_EVAL_MODE_ALL = "all_nodes"
CANDIDATE_EVAL_MODE_ACTIVE_CHIPS = "active_chip_nodes"
CANDIDATE_EVAL_MODES = (CANDIDATE_EVAL_MODE_ALL, CANDIDATE_EVAL_MODE_ACTIVE_CHIPS)